const books = [
  {
    bookID: 1,
    title: "Harry Potter and the Half-Blood Prince (Harry Potter  #6)",
    authors: "J.K. Rowling-Mary GrandPré",
    average_rating: 4.56,
    isbn: 439785960,
    language_code: "eng",
    ratings_count: 1944099,
    price: 230,
  },
  {
    bookID: 2,
    title: "Harry Potter and the Order of the Phoenix (Harry Potter  #5)",
    authors: "J.K. Rowling-Mary GrandPré",
    average_rating: 4.49,
    isbn: 439358078,
    language_code: "eng",
    ratings_count: 1996446,
    price: 231,
  },
  {
    bookID: 3,
    title: "Harry Potter and the Sorcerer's Stone (Harry Potter  #1)",
    authors: "J.K. Rowling-Mary GrandPré",
    average_rating: 4.47,
    isbn: 439554934,
    language_code: "eng",
    ratings_count: 5629932,
    price: 232,
  },
  {
    bookID: 4,
    title: "Harry Potter and the Chamber of Secrets (Harry Potter  #2)",
    authors: "J.K. Rowling",
    average_rating: 4.41,
    isbn: 439554896,
    language_code: "eng",
    ratings_count: 6267,
    price: 233,
  },
  {
    bookID: 5,
    title: "Harry Potter and the Prisoner of Azkaban (Harry Potter  #3)",
    authors: "J.K. Rowling-Mary GrandPré",
    average_rating: 4.55,
    isbn: "043965548X",
    language_code: "eng",
    ratings_count: 2149872,
    price: 234,
  },
  {
    bookID: 8,
    title: "Harry Potter Boxed Set  Books 1-5 (Harry Potter  #1-5)",
    authors: "J.K. Rowling-Mary GrandPré",
    average_rating: 4.78,
    isbn: 439682584,
    language_code: "eng",
    ratings_count: 38872,
    price: 235,
  },
  {
    bookID: 9,
    title:
      'Unauthorized Harry Potter Book Seven News: "Half-Blood Prince" Analysis and Speculation',
    authors: "W. Frederick Zimmerman",
    average_rating: 3.69,
    isbn: 976540606,
    language_code: "en-US",
    ratings_count: 18,
    price: 236,
  },
  {
    bookID: 10,
    title: "Harry Potter Collection (Harry Potter  #1-6)",
    authors: "J.K. Rowling",
    average_rating: 4.73,
    isbn: 439827604,
    language_code: "eng",
    ratings_count: 27410,
    price: 237,
  },
  {
    bookID: 12,
    title:
      "The Ultimate Hitchhiker's Guide: Five Complete Novels and One Story (Hitchhiker's Guide to the Galaxy  #1-5)",
    authors: "Douglas Adams",
    average_rating: 4.38,
    isbn: 517226952,
    language_code: "eng",
    ratings_count: 3602,
    price: 238,
  },
  {
    bookID: 13,
    title: "The Ultimate Hitchhiker's Guide to the Galaxy",
    authors: "Douglas Adams",
    average_rating: 4.38,
    isbn: 345453743,
    language_code: "eng",
    ratings_count: 240189,
    price: 239,
  },
  {
    bookID: 14,
    title:
      "The Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy  #1)",
    authors: "Douglas Adams",
    average_rating: 4.22,
    isbn: 1400052920,
    language_code: "eng",
    ratings_count: 4416,
    price: 240,
  },
  {
    bookID: 16,
    title:
      "The Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy  #1)",
    authors: "Douglas Adams-Stephen Fry",
    average_rating: 4.22,
    isbn: 739322206,
    language_code: "eng",
    ratings_count: 1222,
    price: 241,
  },
  {
    bookID: 18,
    title:
      "The Ultimate Hitchhiker's Guide (Hitchhiker's Guide to the Galaxy #1-5)",
    authors: "Douglas Adams",
    average_rating: 4.38,
    isbn: 517149257,
    language_code: "en-US",
    ratings_count: 2801,
    price: 242,
  },
  {
    bookID: 21,
    title: "A Short History of Nearly Everything",
    authors: "Bill Bryson-William Roberts",
    average_rating: 4.2,
    isbn: "076790818X",
    language_code: "eng",
    ratings_count: 228522,
    price: 243,
  },
  {
    bookID: 22,
    title: "Bill Bryson's African Diary",
    authors: "Bill Bryson",
    average_rating: 3.43,
    isbn: 767915062,
    language_code: "eng",
    ratings_count: 6993,
    price: 244,
  },
  {
    bookID: 23,
    title:
      "Bryson's Dictionary of Troublesome Words: A Writer's Guide to Getting It Right",
    authors: "Bill Bryson",
    average_rating: 3.88,
    isbn: 767910435,
    language_code: "eng",
    ratings_count: 2020,
    price: 245,
  },
  {
    bookID: 24,
    title: "In a Sunburned Country",
    authors: "Bill Bryson",
    average_rating: 4.07,
    isbn: 767903862,
    language_code: "eng",
    ratings_count: 68213,
    price: 246,
  },
  {
    bookID: 25,
    title:
      "I'm a Stranger Here Myself: Notes on Returning to America After Twenty Years Away",
    authors: "Bill Bryson",
    average_rating: 3.9,
    isbn: "076790382X",
    language_code: "eng",
    ratings_count: 47490,
    price: 247,
  },
  {
    bookID: 26,
    title: "The Lost Continent: Travels in Small Town America",
    authors: "Bill Bryson",
    average_rating: 3.83,
    isbn: 60920084,
    language_code: "en-US",
    ratings_count: 43779,
    price: 248,
  },
  {
    bookID: 27,
    title: "Neither Here nor There: Travels in Europe",
    authors: "Bill Bryson",
    average_rating: 3.87,
    isbn: 380713802,
    language_code: "eng",
    ratings_count: 46397,
    price: 249,
  },
  {
    bookID: 28,
    title: "Notes from a Small Island",
    authors: "Bill Bryson",
    average_rating: 3.92,
    isbn: 380727501,
    language_code: "eng",
    ratings_count: 76476,
    price: 250,
  },
  {
    bookID: 29,
    title: "The Mother Tongue: English and How It Got That Way",
    authors: "Bill Bryson",
    average_rating: 3.94,
    isbn: 380715430,
    language_code: "eng",
    ratings_count: 26672,
    price: 251,
  },
  {
    bookID: 30,
    title:
      "J.R.R. Tolkien 4-Book Boxed Set: The Hobbit and The Lord of the Rings",
    authors: "J.R.R. Tolkien",
    average_rating: 4.59,
    isbn: 345538374,
    language_code: "eng",
    ratings_count: 97731,
    price: 252,
  },
  {
    bookID: 31,
    title: "The Lord of the Rings (The Lord of the Rings  #1-3)",
    authors: "J.R.R. Tolkien",
    average_rating: 4.49,
    isbn: 618517650,
    language_code: "eng",
    ratings_count: 1670,
    price: 253,
  },
  {
    bookID: 32,
    title: "The Lord of the Rings (The Lord of the Rings  #1-3)",
    authors: "J.R.R. Tolkien",
    average_rating: 4.49,
    isbn: 618346244,
    language_code: "eng",
    ratings_count: 2819,
    price: 254,
  },
  {
    bookID: 34,
    title: "The Fellowship of the Ring (The Lord of the Rings  #1)",
    authors: "J.R.R. Tolkien",
    average_rating: 4.35,
    isbn: 618346252,
    language_code: "eng",
    ratings_count: 2009749,
    price: 255,
  },
  {
    bookID: 35,
    title: "The Lord of the Rings (The Lord of the Rings  #1-3)",
    authors: "J.R.R. Tolkien-Alan  Lee",
    average_rating: 4.49,
    isbn: 618260587,
    language_code: "en-US",
    ratings_count: 1606,
    price: 256,
  },
  {
    bookID: 36,
    title: "The Lord of the Rings: Weapons and Warfare",
    authors: "Chris   Smith-Christopher  Lee-Richard Taylor",
    average_rating: 4.53,
    isbn: 618391002,
    language_code: "eng",
    ratings_count: 18934,
    price: 257,
  },
  {
    bookID: 37,
    title: "The Lord of the Rings: Complete Visual Companion",
    authors: "Jude Fisher",
    average_rating: 4.5,
    isbn: 618510826,
    language_code: "eng",
    ratings_count: 343,
    price: 258,
  },
  {
    bookID: 38,
    title: "The Lord of the Rings Box Set",
    authors: "J.R.R. Tolkien",
    average_rating: 4.49,
    isbn: 618153977,
    language_code: "eng",
    ratings_count: 216,
    price: 259,
  },
  {
    bookID: 40,
    title: "Cooking with Fernet Branca (Gerald Samper  #1)",
    authors: "James Hamilton-Paterson",
    average_rating: 3.61,
    isbn: "193337201X",
    language_code: "eng",
    ratings_count: 1214,
    price: 260,
  },
  {
    bookID: 45,
    title: "Agile Web Development with Rails: A Pragmatic Guide",
    authors:
      "Dave Thomas-David Heinemeier Hansson-Leon Breedt-Mike Clark-Thomas  Fuchs-Andreas  Schwarz",
    average_rating: 3.89,
    isbn: "097669400X",
    language_code: "eng",
    ratings_count: 1269,
    price: 261,
  },
  {
    bookID: 50,
    title: "Hatchet",
    authors: "Gary Paulsen",
    average_rating: 3.7,
    isbn: 689840926,
    language_code: "eng",
    ratings_count: 254827,
    price: 262,
  },
  {
    bookID: 51,
    title: 'Hatchet: A Guide for Using "Hatchet" in the Classroom',
    authors: "Donna Ickes-Edward Sciranko-Keith Vasconcelles",
    average_rating: 3.97,
    isbn: 1557344493,
    language_code: "eng",
    ratings_count: 35,
    price: 263,
  },
  {
    bookID: 53,
    title: "Guts: The True Stories behind Hatchet and the Brian Books",
    authors: "Gary Paulsen",
    average_rating: 3.87,
    isbn: 385326505,
    language_code: "eng",
    ratings_count: 1996,
    price: 264,
  },
  {
    bookID: 54,
    title: "Molly Hatchet - 5 of the Best",
    authors: "Molly Hatchet",
    average_rating: 4.33,
    isbn: 1575606240,
    language_code: "eng",
    ratings_count: 6,
    price: 265,
  },
  {
    bookID: 55,
    title: "Hatchet Jobs: Writings on Contemporary Fiction",
    authors: "Dale Peck",
    average_rating: 3.48,
    isbn: 1595580271,
    language_code: "en-US",
    ratings_count: 99,
    price: 266,
  },
  {
    bookID: 57,
    title: "A Changeling for All Seasons (Changeling Seasons #1)",
    authors:
      "Angela Knight-Sahara Kelly-Judy Mays-Marteeka Karland-Kate Douglas-Shelby Morgen-Lacey Savage-Kate Hill-Willa Okati",
    average_rating: 3.75,
    isbn: 1595962808,
    language_code: "eng",
    ratings_count: 167,
    price: 267,
  },
  {
    bookID: 58,
    title: "Changeling (Changeling  #1)",
    authors: "Delia Sherman",
    average_rating: 3.6,
    isbn: 670059676,
    language_code: "eng",
    ratings_count: 957,
    price: 268,
  },
  {
    bookID: 59,
    title: "The Changeling Sea",
    authors: "Patricia A. McKillip",
    average_rating: 4.07,
    isbn: 141312629,
    language_code: "eng",
    ratings_count: 4319,
    price: 269,
  },
  {
    bookID: 61,
    title: "The Changeling",
    authors: "Zilpha Keatley Snyder",
    average_rating: 4.17,
    isbn: 595321801,
    language_code: "eng",
    ratings_count: 1155,
    price: 270,
  },
  {
    bookID: 63,
    title: "The Changeling",
    authors: "Kate Horsley",
    average_rating: 3.56,
    isbn: 1590301943,
    language_code: "eng",
    ratings_count: 295,
    price: 271,
  },
];
exports.books = books;
